### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by captkernel** [mhwong2007/C4.5#1]
Where is the program taking the test data from.
Where is the "actual" data mentioned at the end of the result file that the program is predicting a "member_card" for?

**Comment by munhouiani** [comment]
Hi there,

This is a very naive implementation of decision tree. This program is hard coded to take the CUSTOMER.TXT as input dataset, split it into train set and test set (70% v 30%), and all records are labelled. Since then, we can evaluate its performance through the split test set. 

Thanks.

**Comment by captkernel** [comment]
Can you help me print out the decision tree for the program?
